name = "prompt-directory"
compatibility_date = "2024-03-24"

[build]
command = "npm run build"
dist = "dist/prompt-directory"

[site]
bucket = "./dist/prompt-directory"

[env.production]
name = "prompt-directory-prod"

[env.staging]
name = "prompt-directory-staging" 